### ISSUE TITLE
Separated letters without xepersian package

### ISSUE THREAD

**Issue by bahman-mirzakhani** [SajadKazemi/Parsian-TeX#1]
Sometimes it is necessary to include some Persian text in a completely English document. For example, those whose thesis is in English, some of their pages must be in Persian.
According to the example below, the ‍Parsian family font is not responsive and separates the letters.

```tex
\documentclass{article}

\usepackage{lipsum}
\usepackage{ptext}

\usepackage{fontspec}
\newfontfamily{\parsian}{Parsian} % Parsian TeX, Parsian Sans, Parsian Title

\usepackage{bidi}

\begin{document}

	\lipsum[1]

	\setRTL\parsian\selectfont
	\ptext[1]

\end{document}
```

Output:
[test.pdf](https://github.com/SajadKazemi/Parsian-TeX/files/12209501/test.pdf)
[test.log](https://github.com/SajadKazemi/Parsian-TeX/files/12209502/test.log)

**Comment by SajadKazemi** [comment]
Loading Arabic/Persian fonts without specifying the **Script** is likely to result in your text having separated letters.
You'll get the same result (separated letters) with **Arial**, **Calibri**, **Amiri**, **Traditional Arabic** or any other community-standard font. 

### The Answer:
when loading any font with Arabic/Persian support, specify the script. The following code worked for me:
`\newfontfamily{\parsian}[Script=Arabic]{Parsian}`

**Comment by bahman-mirzakhani** [comment]
Thanks. You are right, so I close this issue.
